services:
  # # api:
  # #   build:
  # #     context: ./api/
  # #     dockerfile: Dockerfile
  # #     # args:
  # #     #   DATABASE_URL: ${DATABASE_URL}
  # #   env_file:
  # #     - .env
  # #   ports:
  # #     - "${API_PORT}:3000"
  # #   depends_on:
  # #     - db
  # #   networks:
  # #     - app_net

  db:
    image: postgres:18.0
    container_name: db
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbData:/var/lib/postgresql/
      # Mount initialization scripts
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - app_net

volumes:
  dbData:
networks:
  app_net:
    driver: bridge