name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*     

    # start the docker compose file   
    - name: start docker
      working-directory: .  # root folder
      run: docker compose up -d --build

    # inject env values from github secrets
    - name: create env file for 
      working-directory: .
      run: |
        cat <<EOF > .env
        POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}

        VITE_API_URL=http://api:3000
        EOF

    - name: wait for frontend
      run: npx wait-on http://localhost:3000


    # cache - speed up the time it takes after first run
    - name: get pnpm store path
      id: pnpm-cache
      run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT 

    - uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: pnpm-${{ runner.os }}-${{ hashFiles('e2e/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-${{ runner.os }}-

    # cache - playwright browsers
    - uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('e2e/pnpm-lock.yaml') }}
        restore-keys: |
          playwright-${{ runner.os }}-

    - name: Install dependencies
      working-directory: e2e # use the right folder.
      run: npm install -g pnpm && pnpm install
    - name: Install Playwright Browsers
      working-directory: e2e # use the right folder.
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm exec playwright test
      working-directory: e2e # use the right folder.
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
